FROM node:alpine as base

WORKDIR /app

COPY package*.json ./

# make node modules folder
RUN mkdir -p /app/node_modules
# recursive ownership for user node on all files in app
RUN chown -R node:node /app

RUN npm install yarn

RUN yarn

FROM base as test
RUN yarn
COPY . .
CMD [ "yarn", "test" ]

FROM base as prod
RUN yarn
COPY . .
CMD ["yarn", "build"]

RUN chown -R node:node /app

USER node